export const menuData = [
  {
    category: "Coffee",
    image: "./img/menu-page/coffee-1.jpg",
    name: "Irish coffee",
    description:
      "Fragrant black coffee with Jameson Irish whiskey and whipped milk",
    price: 7.0,
    size: ["200 ml", "300 ml", "400 ml"],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  {
    category: "Coffee",
    image: "./img/menu-page/coffee-2.jpg",
    name: "Kahlua coffee",
    description:
      "Classic coffee with milk and Kahlua liqueur under a cap of frothed milk",
    price: 7.0,
    size: ["200 ml", "300 ml", "400 ml"],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  {
    category: "Coffee",
    image: "./img/menu-page/coffee-3.jpg",
    name: "Honey raf",
    description: "Espresso with frothed milk, cream and aromatic honey",
    price: 5.5,
    size: ["200 ml", "300 ml", "400 ml"],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  {
    category: "Coffee",
    image: "./img/menu-page/coffee-4.jpg",
    name: "Ice cappuccino",
    description: "Cappuccino with soft thick foam in summer version with ice",
    price: 5.0,
    size: ["200 ml", "300 ml", "400 ml"],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  {
    category: "Coffee",
    image: "./img/menu-page/coffee-5.jpg",
    name: "Espresso",
    description: "Classic black coffee",
    price: 4.5,
    size: ["200 ml", "300 ml", "400 ml"],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  {
    category: "Coffee",
    image: "./img/menu-page/coffee-6.jpg",
    name: "Latte",
    description:
      "Espresso coffee with the addition of steamed milk and dense milk foam",
    price: 5.5,
    size: ["200 ml", "300 ml", "400 ml"],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  {
    category: "Coffee",
    image: "./img/menu-page/coffee-7.jpg",
    name: "Latte macchiato",
    description: "Espresso with frothed milk and chocolate",
    price: 5.5,
    size: ["200 ml", "300 ml", "400 ml"],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  {
    category: "Coffee",
    image: "./img/menu-page/coffee-8.jpg",
    name: "Coffee with cognac",
    description: "Fragrant black coffee with cognac and whipped cream",
    price: 6.5,
    size: ["200 ml", "300 ml", "400 ml"],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  {
    category: "Tea",
    image: "./img/menu-page/tea-1.png",
    name: "Moroccan",
    description:
      "Fragrant black tea with the addition of tangerine, cinnamon, honey, lemon and mint",
    price: 4.5,
    size: ["200 ml", "300 ml", "400 ml"],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  {
    category: "Tea",
    image: "./img/menu-page/tea-2.png",
    name: "Ginger",
    description: "Original black tea with fresh ginger, lemon and honey",
    price: 5.0,
    size: ["200 ml", "300 ml", "400 ml"],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  {
    category: "Tea",
    image: "./img/menu-page/tea-3.png",
    name: "Cranberry",
    description: "Invigorating black tea with cranberry and honey",
    price: 5.0,
    size: ["200 ml", "300 ml", "400 ml"],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  {
    category: "Tea",
    image: "./img/menu-page/tea-4.png",
    name: "Sea buckthorn",
    description:
      "Toning sweet black tea with sea buckthorn, fresh thyme and cinnamon",
    price: 5.5,
    size: ["200 ml", "300 ml", "400 ml"],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  {
    category: "Dessert",
    image: "./img/menu-page/dessert-1.png",
    name: "Marble cheesecake",
    description:
      "Philadelphia cheese with lemon zest on a light sponge cake and red currant jam",
    price: 3.5,
    size: ["50 g", "100 g", "200 g"],
    additives: ["Berries", "Nuts", "Jam"],
  },
  {
    category: "Dessert",
    image: "./img/menu-page/dessert-2.png",
    name: "Red velvet",
    description: "Layer cake with cream cheese frosting",
    price: 4.0,
    size: ["50 g", "100 g", "200 g"],
    additives: ["Berries", "Nuts", "Jam"],
  },
  {
    category: "Dessert",
    image: "./img/menu-page/dessert-3.png",
    name: "Cheesecakes",
    description:
      "Soft cottage cheese pancakes with sour cream and fresh berries and sprinkled with powdered sugar",
    price: 4.5,
    size: ["50 g", "100 g", "200 g"],
    additives: ["Berries", "Nuts", "Jam"],
  },
  {
    category: "Dessert",
    image: "./img/menu-page/dessert-4.png",
    name: "Creme brulee",
    description:
      "Delicate creamy dessert in a caramel basket with wild berries",
    price: 4.0,
    size: ["50 g", "100 g", "200 g"],
    additives: ["Berries", "Nuts", "Jam"],
  },
  {
    category: "Dessert",
    image: "./img/menu-page/dessert-5.png",
    name: "Pancakes",
    description: "Tender pancakes with strawberry jam and fresh strawberries",
    price: 4.5,
    size: ["50 g", "100 g", "200 g"],
    additives: ["Berries", "Nuts", "Jam"],
  },
  {
    category: "Dessert",
    image: "./img/menu-page/dessert-6.png",
    name: "Honey cake",
    description: "Classic honey cake with delicate custard",
    price: 4.5,
    size: ["50 g", "100 g", "200 g"],
    additives: ["Berries", "Nuts", "Jam"],
  },
  {
    category: "Dessert",
    image: "./img/menu-page/dessert-7.png",
    name: "Chocolate cake",
    description: "Cake with hot chocolate filling and nuts with dried apricots",
    price: 5.5,
    size: ["50 g", "100 g", "200 g"],
    additives: ["Berries", "Nuts", "Jam"],
  },
  {
    category: "Dessert",
    image: "./img/menu-page/dessert-8.png",
    name: "Black forest",
    description:
      "A combination of thin sponge cake with cherry jam and light chocolate mousse",
    price: 6.5,
    size: ["50 g", "100 g", "200 g"],
    additives: ["Berries", "Nuts", "Jam"],
  },
];
